import type { ArticleCategory } from './articleCategory.js';

export interface CategoryRuleRow {
  keyword: string;
  category: ArticleCategory;
}

// Built-in fallback used to seed the `category_rules` table on first run, and
// used directly for classification if Postgres is unreachable. Order matters:
// the first row whose keyword matches wins.
export const DEFAULT_CATEGORY_RULES: CategoryRuleRow[] = [
  { keyword: 'museum', category: 'museum' },
  { keyword: 'gallery', category: 'museum' },
  { keyword: 'galleries', category: 'museum' },
  { keyword: 'church', category: 'worship' },
  { keyword: 'cathedral', category: 'worship' },
  { keyword: 'chapel', category: 'worship' },
  { keyword: 'mosque', category: 'worship' },
  { keyword: 'synagogue', category: 'worship' },
  { keyword: 'temple', category: 'worship' },
  { keyword: 'monastery', category: 'worship' },
  { keyword: 'abbey', category: 'worship' },
  { keyword: 'gurdwara', category: 'worship' },
  { keyword: 'religious buildings and structures', category: 'worship' },
  { keyword: 'roman catholic', category: 'worship' },
  { keyword: 'dioceses', category: 'worship' },
  { keyword: 'archdiocese', category: 'worship' },
  { keyword: 'parishes', category: 'worship' },
  { keyword: 'park', category: 'park' },
  { keyword: 'garden', category: 'park' },
  { keyword: 'nature reserve', category: 'park' },
  { keyword: 'wildlife', category: 'park' },
  { keyword: 'forest', category: 'park' },
  { keyword: 'listed building', category: 'historic' },
  { keyword: 'heritage', category: 'historic' },
  { keyword: 'historic', category: 'historic' },
  { keyword: 'castle', category: 'historic' },
  { keyword: 'palace', category: 'historic' },
  { keyword: 'fort', category: 'historic' },
  { keyword: 'ruins', category: 'historic' },
  { keyword: 'archaeological', category: 'historic' },
  { keyword: 'houses in', category: 'historic' },
  { keyword: 'skyscraper', category: 'historic' },
  { keyword: 'office buildings', category: 'historic' },
  { keyword: 'mixed-use developments', category: 'historic' },
  { keyword: 'residential buildings', category: 'historic' },
  { keyword: 'high-rise buildings', category: 'historic' },
  { keyword: 'buildings and structures in', category: 'historic' },
  { keyword: 'battles of', category: 'historic' },
  { keyword: 'battles involving', category: 'historic' },
  { keyword: 'university', category: 'education' },
  { keyword: 'college', category: 'education' },
  { keyword: 'school', category: 'education' },
  { keyword: 'academy', category: 'education' },
  { keyword: 'library', category: 'education' },
  { keyword: 'station', category: 'transport' },
  { keyword: 'airport', category: 'transport' },
  { keyword: 'railway', category: 'transport' },
  { keyword: 'bridge', category: 'transport' },
  { keyword: 'canal', category: 'transport' },
  { keyword: 'harbor', category: 'transport' },
  { keyword: 'harbour', category: 'transport' },
  { keyword: 'ports of', category: 'transport' },
  { keyword: 'ports in', category: 'transport' },
  { keyword: 'port of', category: 'transport' },
  { keyword: 'cities in', category: 'city' },
  { keyword: 'cities of', category: 'city' },
  { keyword: 'towns in', category: 'city' },
  { keyword: 'towns of', category: 'city' },
  { keyword: 'townships in', category: 'city' },
  { keyword: 'townships of', category: 'city' },
  { keyword: 'villages in', category: 'city' },
  { keyword: 'villages of', category: 'city' },
  { keyword: 'census-designated places in', category: 'city' },
  { keyword: 'incorporated cities and towns', category: 'city' },
  { keyword: 'unincorporated communities in', category: 'city' },
  { keyword: 'counties in', category: 'city' },
  { keyword: 'metropolitan areas', category: 'city' },
  { keyword: 'metropolitan statistical areas', category: 'city' },
  // Non-US Wikipedia conventions for the same "populated place" concept —
  // discovered while backfilling the towns/townships gap (OurGaia issue: a
  // settlement whose only categories used a different country's naming
  // convention than the US "X in Y" pattern fell through to 'default').
  { keyword: 'municipalities of', category: 'city' },
  { keyword: 'municipalities in', category: 'city' },
  { keyword: 'communes of', category: 'city' },
  { keyword: 'communes in', category: 'city' },
  { keyword: 'civil parishes in', category: 'city' },
  { keyword: 'boroughs in', category: 'city' },
  { keyword: 'hamlets in', category: 'city' },
  { keyword: 'county seats of', category: 'city' },
  { keyword: 'settlements in', category: 'city' },
  { keyword: 'demolished', category: 'demolished' },
  { keyword: 'shopping mall', category: 'shopping' },
  { keyword: 'shopping center', category: 'shopping' },
  { keyword: 'shopping district', category: 'shopping' },
  { keyword: 'ghost town', category: 'ghost-town' },
  { keyword: 'former settlement', category: 'ghost-town' },
  { keyword: 'neighborhoods in', category: 'neighborhood' },
  { keyword: 'districts of', category: 'neighborhood' },
  { keyword: 'sectors of', category: 'neighborhood' },
  { keyword: 'populated places in', category: 'neighborhood' },
  { keyword: 'suburbs of', category: 'neighborhood' },
  { keyword: 'streets in', category: 'neighborhood' },
  { keyword: 'aviation accidents', category: 'plane-crash' },
  { keyword: 'airliner accidents', category: 'plane-crash' },
  { keyword: 'hospitals in', category: 'hospital' },
  { keyword: 'hospital buildings', category: 'hospital' },
  { keyword: 'rivers of', category: 'waterway' },
  { keyword: 'creeks of', category: 'waterway' },
  { keyword: 'streams of', category: 'waterway' },
  { keyword: 'tributaries of', category: 'waterway' },
  { keyword: 'bodies of water', category: 'waterway' },
  { keyword: 'aquifers in', category: 'waterway' },
  { keyword: 'lakes in', category: 'waterway' },
  { keyword: 'reservoirs in', category: 'waterway' },
  { keyword: 'bays of', category: 'waterway' },
  { keyword: 'islands of', category: 'waterway' },
  { keyword: 'canyons and gorges', category: 'landform' },
  { keyword: 'valleys of', category: 'landform' },
  { keyword: 'landforms of', category: 'landform' },
  { keyword: 'hills of', category: 'landform' },
  { keyword: 'mountains of', category: 'landform' },
  { keyword: 'mountain ranges of', category: 'landform' },
  { keyword: 'urban legend', category: 'urban-legend' },
  { keyword: 'folklore', category: 'urban-legend' },
  { keyword: 'ghosts', category: 'urban-legend' },
  { keyword: 'cryptid', category: 'urban-legend' },
  { keyword: 'food and drink', category: 'food-and-drink' },
  { keyword: 'chocolate companies', category: 'food-and-drink' },
  { keyword: 'cuisine of', category: 'food-and-drink' },
  { keyword: 'breweries', category: 'food-and-drink' },
  { keyword: 'wineries', category: 'food-and-drink' },
  { keyword: 'restaurants', category: 'food-and-drink' },
  { keyword: 'distilleries', category: 'food-and-drink' },
  { keyword: 'sculpture', category: 'art' },
  { keyword: 'public art', category: 'art' },
  { keyword: 'murals', category: 'art' },
  { keyword: 'street art', category: 'art' },
  { keyword: 'art installations', category: 'art' },
  { keyword: 'natural disasters', category: 'natural-disaster' },
  { keyword: 'earthquakes in', category: 'natural-disaster' },
  { keyword: 'floods in', category: 'natural-disaster' },
  { keyword: 'wildfires in', category: 'natural-disaster' },
  { keyword: 'tornadoes in', category: 'natural-disaster' },
  { keyword: 'hurricanes in', category: 'natural-disaster' },
  { keyword: 'golf clubs and courses', category: 'sport' },
  { keyword: 'sports venues', category: 'sport' },
  { keyword: 'stadiums in', category: 'sport' },
  { keyword: 'arenas in', category: 'sport' },
  { keyword: 'racetracks in', category: 'sport' },
  { keyword: 'swimming venues', category: 'sport' },
  { keyword: 'athletic', category: 'sport' },
  { keyword: 'athletic conference', category: 'sport' },
  { keyword: 'sports league', category: 'sport' },
  { keyword: 'football clubs', category: 'sport' },
  { keyword: 'association football', category: 'sport' },
  { keyword: 'rugby clubs', category: 'sport' },
  { keyword: 'cricket clubs', category: 'sport' },
  { keyword: 'basketball teams', category: 'sport' },
  { keyword: 'baseball teams', category: 'sport' },
  { keyword: 'sports clubs', category: 'sport' },
  { keyword: 'league clubs', category: 'sport' },
  { keyword: 'sports teams', category: 'sport' },
  { keyword: 'air traffic control', category: 'infrastructure' },
  { keyword: 'power stations in', category: 'infrastructure' },
  { keyword: 'power plants in', category: 'infrastructure' },
  { keyword: 'sewage', category: 'infrastructure' },
  { keyword: 'water treatment', category: 'infrastructure' },
  { keyword: 'telecommunications', category: 'infrastructure' },
  { keyword: 'radio stations in', category: 'infrastructure' },
  { keyword: 'television stations in', category: 'infrastructure' },
  { keyword: 'pipelines', category: 'infrastructure' },
  { keyword: 'substations', category: 'infrastructure' },
  { keyword: 'area codes in', category: 'infrastructure' },
  { keyword: 'electric power companies', category: 'infrastructure' },
  { keyword: 'power companies of', category: 'infrastructure' },
  { keyword: 'energy companies', category: 'infrastructure' },
  { keyword: 'government-owned energy', category: 'infrastructure' },
  { keyword: 'festivals in', category: 'event' },
  { keyword: 'recurring events', category: 'event' },
  { keyword: 'annual events', category: 'event' },
  { keyword: 'fairs in', category: 'event' },
  { keyword: 'parades in', category: 'event' },
  { keyword: 'convention centers', category: 'event' },
  { keyword: 'assembly plants', category: 'industry' },
  { keyword: 'manufacturing', category: 'industry' },
  { keyword: 'factories', category: 'industry' },
  { keyword: 'industrial buildings', category: 'industry' },
  { keyword: 'mills in', category: 'industry' },
  { keyword: 'refineries', category: 'industry' },
  { keyword: 'canneries', category: 'industry' },
  { keyword: 'foundries', category: 'industry' },
  { keyword: 'central banks', category: 'industry' },
  { keyword: 'federal reserve', category: 'industry' },
  { keyword: 'banks of', category: 'industry' },
  { keyword: 'banks established', category: 'industry' },
  { keyword: 'financial services companies', category: 'industry' },
  { keyword: 'agriculture companies', category: 'industry' },
  { keyword: 'investment companies', category: 'industry' },
  { keyword: 'organisations based in', category: 'industry' },
  { keyword: 'economy of', category: 'industry' },
  { keyword: 'non-profit organizations', category: 'community' },
  { keyword: 'charities', category: 'community' },
  { keyword: 'community organizations', category: 'community' },
  { keyword: 'historical societies', category: 'community' },
  { keyword: 'volunteer', category: 'community' },
  { keyword: 'advocacy', category: 'community' },
  { keyword: 'newspapers published in', category: 'community' },
  { keyword: 'magazines published in', category: 'community' },
  { keyword: 'mass media in', category: 'community' },
  { keyword: 'city council', category: 'community' },
  { keyword: 'government of', category: 'community' },
  { keyword: 'city councils', category: 'community' },
  { keyword: 'ministries of', category: 'community' },
  { keyword: 'government agencies', category: 'community' },
  { keyword: 'diplomatic missions', category: 'community' },
  { keyword: 'national lower houses', category: 'community' },
  { keyword: 'national upper houses', category: 'community' },
  { keyword: 'politics of', category: 'community' },
  { keyword: 'shipwrecks', category: 'maritime' },
  { keyword: 'ships built in', category: 'maritime' },
  { keyword: 'naval vessels', category: 'maritime' },
  { keyword: 'maritime incidents', category: 'maritime' },
  { keyword: 'submarines of', category: 'maritime' },
  { keyword: 'destroyers', category: 'maritime' },
  { keyword: 'battleships', category: 'maritime' },
  { keyword: 'cruisers', category: 'maritime' },
  { keyword: 'video game companies', category: 'tech' },
  { keyword: 'software companies', category: 'tech' },
  { keyword: 'technology companies', category: 'tech' },
  { keyword: 'semiconductor', category: 'tech' },
  { keyword: 'biotechnology companies', category: 'tech' },
  { keyword: 'computer science', category: 'tech' },
  { keyword: 'internet companies', category: 'tech' },
  { keyword: 'artificial intelligence', category: 'tech' },
  { keyword: 'integrated development environments', category: 'tech' },
  { keyword: 'cloud computing', category: 'tech' },
  { keyword: 'music venues', category: 'performing-arts' },
  { keyword: 'theatres in', category: 'performing-arts' },
  { keyword: 'theaters in', category: 'performing-arts' },
  { keyword: 'concert halls', category: 'performing-arts' },
  { keyword: 'opera houses', category: 'performing-arts' },
  { keyword: 'performing arts', category: 'performing-arts' },
  { keyword: 'amphitheaters in', category: 'performing-arts' },
  { keyword: 'trails in', category: 'trail' },
  { keyword: 'hiking trails', category: 'trail' },
  { keyword: 'rail trails', category: 'trail' },
  { keyword: 'walking trails', category: 'trail' },
  { keyword: 'recording studios', category: 'recording-studio' },
  { keyword: 'record labels', category: 'recording-studio' },
  { keyword: 'music recording', category: 'recording-studio' },
  { keyword: 'casinos in', category: 'entertainment' },
  { keyword: 'entertainment venues', category: 'entertainment' },
  { keyword: 'amusement parks', category: 'entertainment' },
  { keyword: 'nightclubs', category: 'entertainment' },
];

// Built-in fallback for title-based classification (used when no category
// match is found). Same first-match-wins ordering as above.
export const DEFAULT_TITLE_RULES: CategoryRuleRow[] = [
  { keyword: 'museum', category: 'museum' },
  { keyword: 'gallery', category: 'museum' },
  { keyword: 'church', category: 'worship' },
  { keyword: 'cathedral', category: 'worship' },
  { keyword: 'chapel', category: 'worship' },
  { keyword: 'mosque', category: 'worship' },
  { keyword: 'synagogue', category: 'worship' },
  { keyword: 'temple', category: 'worship' },
  { keyword: 'monastery', category: 'worship' },
  { keyword: 'abbey', category: 'worship' },
  { keyword: 'gurdwara', category: 'worship' },
  { keyword: 'cemetery', category: 'worship' },
  { keyword: 'park', category: 'park' },
  { keyword: 'garden', category: 'park' },
  { keyword: 'shoreline', category: 'park' },
  { keyword: 'nature reserve', category: 'park' },
  { keyword: 'wildlife', category: 'park' },
  { keyword: 'forest', category: 'park' },
  { keyword: 'open space', category: 'park' },
  { keyword: 'recreation area', category: 'park' },
  { keyword: 'mansion', category: 'historic' },
  { keyword: 'city hall', category: 'historic' },
  { keyword: 'hall of justice', category: 'historic' },
  { keyword: 'historic', category: 'historic' },
  { keyword: 'castle', category: 'historic' },
  { keyword: 'palace', category: 'historic' },
  { keyword: 'fort', category: 'historic' },
  { keyword: 'ruins', category: 'historic' },
  { keyword: 'rancho', category: 'historic' },
  { keyword: 'house', category: 'historic' },
  { keyword: 'tower', category: 'historic' },
  { keyword: 'plaza', category: 'historic' },
  { keyword: '(building)', category: 'historic' },
  { keyword: 'university', category: 'education' },
  { keyword: 'college', category: 'education' },
  { keyword: 'high school', category: 'education' },
  { keyword: 'school', category: 'education' },
  { keyword: 'academy', category: 'education' },
  { keyword: 'library', category: 'education' },
  { keyword: 'institute', category: 'education' },
  { keyword: 'hospital', category: 'hospital' },
  { keyword: 'medical center', category: 'hospital' },
  { keyword: 'station', category: 'transport' },
  { keyword: 'airport', category: 'transport' },
  { keyword: 'railway', category: 'transport' },
  { keyword: 'bridge', category: 'transport' },
  { keyword: 'canal', category: 'transport' },
  { keyword: 'port', category: 'transport' },
  { keyword: 'harbour', category: 'transport' },
  { keyword: 'creek', category: 'waterway' },
  { keyword: 'river', category: 'waterway' },
  { keyword: 'stream', category: 'waterway' },
  { keyword: 'lake', category: 'waterway' },
  { keyword: 'reservoir', category: 'waterway' },
  { keyword: 'slough', category: 'waterway' },
  { keyword: 'bay', category: 'waterway' },
  { keyword: 'estuary', category: 'waterway' },
  { keyword: 'island', category: 'waterway' },
  { keyword: 'stadium', category: 'sport' },
  { keyword: 'speedway', category: 'sport' },
  { keyword: 'golf course', category: 'sport' },
  { keyword: 'country club', category: 'sport' },
  { keyword: 'arena', category: 'sport' },
  { keyword: 'theater', category: 'performing-arts' },
  { keyword: 'theatre', category: 'performing-arts' },
  { keyword: 'amphitheater', category: 'performing-arts' },
  { keyword: 'amphitheatre', category: 'performing-arts' },
  { keyword: 'music hall', category: 'performing-arts' },
  { keyword: 'concert hall', category: 'performing-arts' },
  { keyword: 'opera house', category: 'performing-arts' },
  { keyword: 'trail', category: 'trail' },
  { keyword: 'trailhead', category: 'trail' },
  { keyword: 'recording studio', category: 'recording-studio' },
  { keyword: 'record label', category: 'recording-studio' },
  { keyword: 'casino', category: 'entertainment' },
  { keyword: 'nightclub', category: 'entertainment' },
  { keyword: 'convention center', category: 'event' },
  { keyword: 'metropolitan area', category: 'city' },
  { keyword: 'township', category: 'city' },
  { keyword: 'federal reserve', category: 'industry' },
  { keyword: 'reserve bank', category: 'industry' },
  { keyword: 'hotel', category: 'food-and-drink' },
  { keyword: 'inn', category: 'food-and-drink' },
  { keyword: 'city council', category: 'community' },
  { keyword: 'list of ambassadors', category: 'community' },
  { keyword: 'ministry of', category: 'community' },
  { keyword: 'department of', category: 'community' },
  { keyword: 'senate of', category: 'community' },
  { keyword: 'national assembly', category: 'community' },
  { keyword: 'city county', category: 'community' },
  { keyword: 'energy group', category: 'infrastructure' },
  { keyword: 'power company', category: 'infrastructure' },
  { keyword: 'energy company', category: 'infrastructure' },
  { keyword: 'power and lighting', category: 'infrastructure' },
  { keyword: 'bank rwanda', category: 'industry' },
  { keyword: 'bank kenya', category: 'industry' },
  { keyword: 'bank nigeria', category: 'industry' },
  { keyword: 'bank africa', category: 'industry' },
  { keyword: 'avenue', category: 'neighborhood' },
  { keyword: ' street', category: 'neighborhood' },
  { keyword: 'highrise', category: 'neighborhood' },
  { keyword: 'high rise', category: 'neighborhood' },
  { keyword: 'housing estate', category: 'neighborhood' },
];
